version: '3.6'

services:
  sql-server:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql
    environment:
      SA_PASSWORD: ZBjcVbatxSkbs9Y34ws4fGQ94yGEaEv2
      ACCEPT_EULA: "Y"