version: '3.4'

services:
  # nginx:
  #   image: nginx:stable-alpine
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - ./wordpress:/var/www/html:delegated

  db:
    image: mysql:5.7
    ports: 
      - '8001:3306'
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - ./db:/var/lib/mysql
    restart: always
  
  wp:
    image: wordpress:5.6-php7.4
    links:
      - db:mysql
    environment:
      WORDPRESS_DB_HOST: DB
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    ports:
      - 80:80
    volumes:
      - ./data:/var/www/html
    depends_on:
      - db
    restart: always

