version: "3.6"

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 2712:8080
      - 50000:50000
    container_name: jenkins
    restart: always
    volumes: 
      - ./setting/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker