version: "3.5"

services:
  mysql-db:
    platform: linux/x86_64
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'dev'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'thai1202'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'thai1202root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '8008:3306'
      # Where our data will be persisted
    volumes:
      - mysql-db:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
volumes:
  mysql-db: